### ISSUE TITLE
Header section theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#111]
## Description
> As a customer, I want the header to be styled with flat design like the snapshot bellow:  

![header](https://cloud.githubusercontent.com/assets/3749521/24700733/fb0742aa-19ef-11e7-9a88-4101cfb3b718.png)

> As a customer, I want the dropdown menu to slide down on click like the snapshot bellow: 

![dopdown-menu](https://cloud.githubusercontent.com/assets/3749521/24700842/50ffa4ae-19f0-11e7-8172-138edf271d1b.png)

> As a customer, I want the styling to be responsive for different viewport sizes.

## Acceptance Criteria
- [x] All menu links should be wired
- [x] Vertical menu on small size resolutions
- [x] A test site link is posted in a comment

**Comment by achraf-jeday** [comment]
**Header issues that should be dealt with:**

- The user account menu not printing the 'active' and 'is-active' classes of the `<li>` and `<a>` elements respectively (when 'My account' menu item is active).

- The commerce cart sub-module not printing the total price raw value in the order summary section (`cart-block--summary`) of the cart block.

**Comment by achraf-jeday** [comment]
Test site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-185.probo.build/
