### ISSUE TITLE
Carousel & Call for action sections theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#114]
## Description
> Create a fully responsive boxed layout for the different block sections

![carousel](https://cloud.githubusercontent.com/assets/3749521/24701629/03db204c-19f3-11e7-8c19-ced291d45bc1.png)

## Acceptance Criteria
- [x] The Slideshow styles and functionality should be implemented.
- [x] The 'Call to Action Banner' styles should be implemented
- [x] The slideshow must be responsive
- [x] A test site link is posted in a comment.

**Comment by achraf-jeday** [comment]
There is a bug in the views module (just a guess) which is causing empty image fields to display as a blank HTML container even after checking the 'hide if empty' checkbox in the settings of the field.

**Comment by achraf-jeday** [comment]
Test site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-208.probo.build/
