### ISSUE TITLE
Product details page theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#121]
## Description
> As a customer, When I open **/product/1?v=1**, I want to see the product details page looks like the screenshot bellow:

![product-details](https://cloud.githubusercontent.com/assets/3749521/24708677/7928aaec-1a0f-11e7-9d2b-264bcc689d58.png)
## Acceptance Criteria
- [x] A breadcrumb must be displayed on the top of the shop content
- [x] The breadcrumb must displays a location that looks like this: **Home -> Shop -> CategoryName -> ProductName**
- [x] The product image must be aligned to the left
- [x] The product title, price, add to cart botton, product category and the description must be aligned to right
- [x] The title and price must be aligned horizontally in the same row
- [x] In the sidebar, **Latest Products** block msut be under **Product Category**
- [x] All the sections of the page must be responsive
- [x] A test site link is posted in a comment

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-214.probo.build/

**Comment by achraf-jeday** [comment]
Test Site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-288.probo.build/
