### ISSUE TITLE
Cart page theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#184]
## Description
> As a customer, When I open **/cart**, I want to see the cart page looks like the screenshot bellow:
![cart](https://cloud.githubusercontent.com/assets/3749521/25049887/f63e8a50-213b-11e7-8d8f-31ed3ae965c1.png)

## Acceptance Criteria
- [x] All the sections of the page must be responsive
- [x] A test site link is posted in a comment

**Comment by ihebattia** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-251.probo.build/cart
