### ISSUE TITLE
Create a site map page

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#248]
## Description 
> As a customer, when I open **/site-map**, I want to see a list of the website page links displayed.

## Acceptance Criteria
- [x] When I open **/site-map**, a site map page must be displayed and populated with a list of the website page links
- [x] The page name must be "Site map"
- [x] The page link must be add to the footer menu
- [x] A test link is posted in a comment

**Comment by achraf-jeday** [comment]
Test Site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-277.probo.build/
