### ISSUE TITLE
Display friendly URLs

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#249]
## Description
> As a developer, I want to enable friendly URLs option of all website URLs.

## Acceptance Criteria
- [x] To access a product details, the URL must be like **/shop/[product-name]** instead if **/product/1**
- [x] When I open **/product/1**, I should see the breadcrumb displayed like: Home > shop > [ProductName]
- [x] A site test link is posted in a comment

**Comment by achraf-jeday** [comment]
Test site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-272.probo.build/
